Project 1: Customer Research & Market Insights Analytics


COMPANY SCENARIO

You are a Junior Data Scientist working for a market research and business consulting company.

The company helps businesses understand their customers, improve products, and make smarter business decisions using data.

A new client wants to understand customer behavior, satisfaction, purchasing patterns, and factors affecting customer loyalty.

Your responsibility is to analyze the survey and customer data to provide actionable business insights.

PROJECT STRUCTURE (DATA SCIENCE PIPELINE)
SECTION 1: DATA INSPECTION
Objective: Understand the dataset before analysis.

Tasks
Load dataset
Display first and last rows
Check dataset dimensions
Display data types
Identify missing values
Check duplicate records
Generate descriptive statistics


SECTION 2: DATA CLEANING
Objective: Ensure high-quality data for analysis.

Tasks
Remove duplicate responses
Handle missing values
Standardize gender entries
Standardize customer location names
Convert income into numeric format
Remove impossible ages
Handle inconsistent satisfaction ratings

Note: These tasks are not limited.

SECTION 3: EXPLORATORY DATA ANALYSIS (EDA)
Objective: Understand customer behaviour and business opportunities.

Required Analysis
1. Customer Age Distribution

2. Customer Satisfaction Ratings

3. Average Spending by Customer Segment

4. Income vs Annual Spending

5. Customer Retention by Region

6. Preferred Communication Channel

7. Correlation Heatmap

Add Any Other Two Visualizations that help answer important business questions.

BUSINESS QUESTIONS
Which customer segment should the client target?
What factors drive customer satisfaction?
Which regions generate the highest customer loyalty?
Does income influence spending behaviour?
Which communication channel should marketing prioritize?
Which customer groups are at risk of leaving?


FINAL RECOMMENDATIONS

Provide at least 5 business recommendations.


Expected Deliverables

Cleaned Dataset
Jupyter Notebook
Full ReadMe documentation
Presentation slides
All available in the submitted Git repository link

In [1]:
# ==========================================
# SECTION 1: DATA INSPECTION
# ==========================================

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# Ignore warning messages
warnings.filterwarnings("ignore")


# ------------------------------------------
# Load Dataset
# ------------------------------------------

# Read the customer shopping dataset
customers = pd.read_csv("shopping_trends.csv")

# Create a working copy of the dataset
clean = customers.copy()


# ------------------------------------------
# Display First Five Rows
# ------------------------------------------

print("FIRST FIVE ROWS")
display(clean.head())


# ------------------------------------------
# Display Last Five Rows
# ------------------------------------------

print("\nLAST FIVE ROWS")
display(clean.tail())


# ------------------------------------------
# Check Dataset Dimensions
# ------------------------------------------

print("\nDATASET DIMENSIONS")
print(f"Rows: {clean.shape[0]}")
print(f"Columns: {clean.shape[1]}")


# ------------------------------------------
# Display Column Names
# ------------------------------------------

print("\nCOLUMN NAMES")
print(clean.columns)


# ------------------------------------------
# Display Data Types
# ------------------------------------------

print("\nDATA TYPES")
display(clean.dtypes)


# ------------------------------------------
# Check Missing Values
# ------------------------------------------

print("\nMISSING VALUES")
display(clean.isnull().sum())


# ------------------------------------------
# Check Duplicate Records
# ------------------------------------------

print("\nDUPLICATE RECORDS")
print(clean.duplicated().sum())


# ------------------------------------------
# Generate Descriptive Statistics
# ------------------------------------------

print("\nDESCRIPTIVE STATISTICS")
display(clean.describe(include="all"))

FIRST FIVE ROWS

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

LAST FIVE ROWS

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

DATASET DIMENSIONS
Rows: 3900
Columns: 18

COLUMN NAMES
Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

DATA TYPES

Customer ID                 int64
Age                         int64
Gender                     object
Item Purchased             object
Category                   object
Purchase Amount (USD)       int64
Location                   object
Size                       object
Color                      object
Season                     object
Review Rating             float64
Subscription Status        object
Shipping Type              object
Discount Applied           object
Promo Code Used            object
Previous Purchases          int64
Payment Method             object
Frequency of Purchases     object
dtype: object

MISSING VALUES

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

DUPLICATE RECORDS
0

DESCRIPTIVE STATISTICS

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [2]:
# ==========================================
# SECTION 2: DATA CLEANING
# ==========================================


# Create a working copy of the dataset
clean = customers.copy()


# ------------------------------------------
# 1. Remove Duplicate Records
# ------------------------------------------

print("DUPLICATE RECORDS BEFORE CLEANING")
print(clean.duplicated().sum())

# Remove duplicate records
clean = clean.drop_duplicates()

print("\nDUPLICATE RECORDS AFTER CLEANING")
print(clean.duplicated().sum())


# ------------------------------------------
# 2. Handle Missing Values
# ------------------------------------------

print("\nMISSING VALUES BEFORE CLEANING")
display(clean.isnull().sum())

# Remove rows with missing values
clean = clean.dropna()

print("\nMISSING VALUES AFTER CLEANING")
display(clean.isnull().sum())


# ------------------------------------------
# 3. Standardize Gender
# ------------------------------------------

# Remove extra spaces
# Convert gender values to uppercase

clean["Gender"] = (
    clean["Gender"]
    .str.strip()
    .str.upper()
)


# ------------------------------------------
# 4. Standardize Customer Locations
# ------------------------------------------

# Remove unnecessary spaces

clean["Location"] = (
    clean["Location"]
    .str.strip()
)


# ------------------------------------------
# 5. Convert Purchase Amount into Numeric Format
# ------------------------------------------

clean["Purchase Amount (USD)"] = pd.to_numeric(
    clean["Purchase Amount (USD)"],
    errors="coerce"
)


# ------------------------------------------
# 6. Remove Impossible Ages
# ------------------------------------------

# Keep only realistic customer ages

clean = clean[
    (clean["Age"] >= 18) &
    (clean["Age"] <= 100)
]


# ------------------------------------------
# 7. Standardize Review Ratings
# ------------------------------------------

clean["Review Rating"] = pd.to_numeric(
    clean["Review Rating"],
    errors="coerce"
)


# ------------------------------------------
# 8. Final Data Cleaning Check
# ------------------------------------------

print("\nFINAL DATASET INFORMATION")
clean.info()

print("\nFIRST FIVE ROWS OF CLEANED DATASET")
display(clean.head())

DUPLICATE RECORDS BEFORE CLEANING
0

DUPLICATE RECORDS AFTER CLEANING
0

MISSING VALUES BEFORE CLEANING

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

MISSING VALUES AFTER CLEANING

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

FINAL DATASET INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

FIRST FIVE ROWS OF CLEANED DATASET

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,MALE,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,MALE,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,MALE,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,MALE,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,MALE,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually